### PR TITLE
finished moving authorization middleware into authorization folder

### PR DESCRIPTION
**Pull request by tedtaemin**

### CODE REVIEW

**Review by reubenkirsh — APPROVED** [review]

**Review by reubenkirsh — APPROVED** [review]
This looks great, just like we wanted it

**Review by reubenkirsh — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]

**Review by MxJRd — APPROVED** [review]
LGTM

**Comment by koderka2020** [comment]
Authorization refactored

**Review by koderka2020 — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]

**Review by koderka2020 — APPROVED** [review]
LGTM

**Pull request merged**
